name: 'Discord Workflow Status Notifier'
description: 'A GitHub action to report workflow and job status to a Discord Webhook'
author: 'Braydon Hall'

inputs:
  github-token:
    description: 'GitHub Token'
    required: true

  discord-webhook:
    description: 'The WebHook URL to call. Should be stored in Secrets on the Repository'
    required: true

  username:
    description: 'Overrides the current username of the webhook'
    required: false
    default: 'GitHub Actions'

  avatar-url:
    description: 'Overrides the current avatar of the webhook'
    required: false
    default: 'https://avatars0.githubusercontent.com/u/44036562?s=200&v=4'

  title:
    description: 'Overrides the default title. Include the status in the title by adding the {{STATUS}} placeholder.'
    required: false
  
  description:
    description: 'The message to display. Include the status in the description by adding the {{STATUS}} placeholder'
    required: false
  
  include-details:
    description: 'Whether or not to include the individual job status breakdown of the Workflow run'
    required: false
    default: 'true'
  
  color-success:
    description: 'Overrides the default success color. Any valid hex-color-code. E.g. #17cf48, 17cf48, 0x17cf48'
    required: false
    default: '17cf48'
  
  color-failure:
    description: 'Overrides the default failure color. Any valid hex-color-code. E.g. #17cf48, 17cf48, 0x17cf48'
    required: false
    default: 'e72727'

  color-cancelled:
    description: 'Overrides the default cancelled color. Any valid hex-color-code. E.g. #17cf48, 17cf48, 0x17cf48'
    required: false
    default: 'd3d3d3'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'message-square'
  color: 'gray-dark'